### ISSUE TITLE
32 bit app or 64 app containing 32 bit dll is not working  on 64 bit container

### ISSUE THREAD

**Issue by david0718** [cloudfoundry/hwc#14]
Background:
We have migrated some legacy .net project. These projects could be running in IIS with enable32BitAppOnWin64 set to "true" for the iis pool.

But in hwc_buildpack, it is not working for these project. And hwc_build pack use this hwc project.
As I know this hwc project invoke the hosted web core with applicationHost.config, I checked the code  as below:
<applicationPools>	    <applicationPools>
		<add name="AppPool{{.Config.Port}}" managedRuntimeVersion="v4.0" managedPipelineMode="Integrated" CLRConfigFile="{{.Config.AspnetConfigPath}}" autoStart="true" startMode="AlwaysRunning" />

If possbile this could be solved as below"

<add name="AppPool{{.Config.Port}}" managedRuntimeVersion="v4.0" managedPipelineMode="Integrated" CLRConfigFile="{{.Config.AspnetConfigPath}}" autoStart="true" startMode="AlwaysRunning" enable32BitAppOnWin64="true" />

Looking forward to your response. :）

Thanks
David

**Comment by c-abramson** [comment]
Hey @david0718! We'd like to look into this. In your issue, you have mentioned some code snippets but they do not appear! Could you provide the code snippets from your original post?

**Comment by david0718** [comment]
@c-abramson Hey, in IIS there is a enable32BitAppOnWin64 property to set in IIS pool to support such kind of case. With microsoft's docment, hwc and iis full adopt the same design for the applicationHost.config. 

I tried recompiling the modified hwc and changed the hwc_buildpack to point to the modified zip. It is not working. I am not sure it is not supported by hwc or some mistake I made when modify the build pack. 

the code sninppets as below
Original:
		<add name="AppPool{{.Config.Port}}" managedRuntimeVersion="v4.0" managedPipelineMode="Integrated" CLRConfigFile="{{.Config.AspnetConfigPath}}" autoStart="true" startMode="AlwaysRunning" />

enable32BitAppOnWin64 added:

<add name="AppPool{{.Config.Port}}" managedRuntimeVersion="v4.0" managedPipelineMode="Integrated" CLRConfigFile="{{.Config.AspnetConfigPath}}" autoStart="true" startMode="AlwaysRunning" enable32BitAppOnWin64="true" />

**Comment by TisVictress** [comment]
@david0718  We tried to modify HWC with the `enable32BitAppOnWin64` flag and we couldn't get it to work either.  We also suspect that this is not supported in HWC.

**Comment by david0718** [comment]
@TisVictress 
Thanks for your work and response, maybe it is not supported in HWC. I agree with you.
Then in old .Net code migration , we should rebuild the library to support 64bit with any cpu target.
Anyway we have a solution for the migration.

Thanks again and we could close this issue.

David
